php:7.2-fpm-alpineに変更

diff --git a/wordpress/Dockerfile b/wordpress/Dockerfile
--- a/wordpress/Dockerfile
+++ b/wordpress/Dockerfile
@@ -1,36 +1,92 @@
-FROM php:7.2-apache
-RUN apt-get update && apt-get -y install git
-RUN apt-get -q -y install default-mysql-client
-RUN docker-php-ext-install pdo_mysql mysqli
+FROM php:7.2-fpm-alpine
 
-RUN apt-get update && apt-get install -y libmcrypt-dev \
-    && pecl install mcrypt-1.0.2 \
-    && docker-php-ext-enable mcrypt
+# persistent dependencies
+RUN apk add --no-cache \
+    # in theory, docker-entrypoint.sh is POSIX-compliant, but priority is a working, consistent image
+    bash \
+    # BusyBox sed is not sufficient for some of our sed expressions
+    sed \
+    # Ghostscript is required for rendering PDF previews
+    ghostscript \
+    # Alpine package for "imagemagick" contains ~120 .so files, see: https://github.com/docker-library/wordpress/pull/497
+    imagemagick
 
-RUN docker-php-ext-install \
-    mbstring \
-    json \
-    simplexml \
-    dom \
-    fileinfo \
-    hash \
-    libxml2 \
-    libxml2-devel \
-    xml \
-    iconv
-
-RUN apt-get install -y \
-    libfreetype6-dev \
-    libjpeg62-turbo-dev \
-    libmcrypt-dev \
+# install the PHP extensions we need (https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions)
+RUN set -ex; \
+    \
+    apk add --no-cache --virtual .build-deps \
+    $PHPIZE_DEPS \
+    freetype-dev \
+    imagemagick-dev \
+    libjpeg-turbo-dev \
     libpng-dev \
-    mailutils \
-    memcached \
-    msmtp \
-    msmtp-mta \
-    openssl \
-    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
-    && docker-php-ext-install -j$(nproc) gd exif
+    ; \
+    \
+    docker-php-ext-configure gd --with-freetype-dir=/usr --with-jpeg-dir=/usr --with-png-dir=/usr; \
+    docker-php-ext-install -j "$(nproc)" \
+    bcmath \
+    exif \
+    gd \
+    mysqli \
+    zip \
+    ; \
+    pecl install imagick-3.4.4; \
+    docker-php-ext-enable imagick; \
+    \
+    runDeps="$( \
+    scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
+    | tr ',' '\n' \
+    | sort -u \
+    | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
+    )"; \
+    apk add --virtual .wordpress-phpexts-rundeps $runDeps; \
+    apk del .build-deps
+
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN set -eux; \
+    docker-php-ext-enable opcache; \
+    { \
+    echo 'opcache.memory_consumption=128'; \
+    echo 'opcache.interned_strings_buffer=8'; \
+    echo 'opcache.max_accelerated_files=4000'; \
+    echo 'opcache.revalidate_freq=2'; \
+    echo 'opcache.fast_shutdown=1'; \
+    } > /usr/local/etc/php/conf.d/opcache-recommended.ini
+# https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
+RUN { \
+    # https://www.php.net/manual/en/errorfunc.constants.php
+    # https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
+    echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+    echo 'display_errors = Off'; \
+    echo 'display_startup_errors = Off'; \
+    echo 'log_errors = On'; \
+    echo 'error_log = /dev/stderr'; \
+    echo 'log_errors_max_len = 1024'; \
+    echo 'ignore_repeated_errors = On'; \
+    echo 'ignore_repeated_source = Off'; \
+    echo 'html_errors = Off'; \
+    } > /usr/local/etc/php/conf.d/error-logging.ini
+
+
+ENV WORDPRESS_VERSION 5.4.2
+ENV WORDPRESS_SHA1 e5631f812232fbd45d3431783d3db2e0d5670d2d
+
+RUN set -ex; \
+    curl -o wordpress.tar.gz -fSL "https://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz"; \
+    echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c -; \
+    # upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
+    tar -xzf wordpress.tar.gz -C /usr/src/; \
+    rm wordpress.tar.gz; \
+    chown -R www-data:www-data /usr/src/wordpress; \
+    # pre-create wp-content (and single-level children) for folks who want to bind-mount themes, etc so permissions are pre-created properly instead of root:root
+    mkdir wp-content; \
+    for dir in /usr/src/wordpress/wp-content/*/; do \
+    dir="$(basename "${dir%/}")"; \
+    mkdir "wp-content/$dir"; \
+    done; \
+    chown -R www-data:www-data wp-content; \
+    chmod -R 777 wp-content
 
 VOLUME /var/www/html
 
@@ -38,4 +94,5 @@ COPY docker-entrypoint.sh /usr/local/bin/
 
 ENTRYPOINT ["docker-entrypoint.sh"]
 CMD ["php-fpm"]
+
 EXPOSE 80
