chenge dockerfile

diff --git a/wordpress/Dockerfile b/wordpress/Dockerfile
--- a/wordpress/Dockerfile
+++ b/wordpress/Dockerfile
@@ -1,42 +1,102 @@
-# docker-hubからOSのイメージ引込
-FROM centos:latest
+FROM php:7.2-fpm
 
-# サーバの日付合わせ
-RUN /bin/cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
+# persistent dependencies
+RUN set -eux; \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+    # Ghostscript is required for rendering PDF previews
+    ghostscript \
+    ; \
+    rm -rf /var/lib/apt/lists/*
 
-# epel-releaseのインストール
-RUN yum install -y epel-release &&\
-    yum clean all
+# install the PHP extensions we need (https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions)
+RUN set -ex; \
+    \
+    savedAptMark="$(apt-mark showmanual)"; \
+    \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+    libfreetype6-dev \
+    libjpeg-dev \
+    libmagickwand-dev \
+    libpng-dev \
+    ; \
+    \
+    docker-php-ext-configure gd --with-freetype-dir=/usr --with-jpeg-dir=/usr --with-png-dir=/usr; \
+    docker-php-ext-install -j "$(nproc)" \
+    bcmath \
+    exif \
+    gd \
+    mysqli \
+    zip \
+    ; \
+    pecl install imagick-3.4.4; \
+    docker-php-ext-enable imagick; \
+    \
+    # reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
+    apt-mark auto '.*' > /dev/null; \
+    apt-mark manual $savedAptMark; \
+    ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
+    | awk '/=>/ { print $3 }' \
+    | sort -u \
+    | xargs -r dpkg-query -S \
+    | cut -d: -f1 \
+    | sort -u \
+    | xargs -rt apt-mark manual; \
+    \
+    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+    rm -rf /var/lib/apt/lists/*
 
-# remiのインストール
-RUN rpm -ivh http://ftp.riken.jp/Linux/remi/enterprise/remi-release-8.rpm
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN set -eux; \
+    docker-php-ext-enable opcache; \
+    { \
+    echo 'opcache.memory_consumption=128'; \
+    echo 'opcache.interned_strings_buffer=8'; \
+    echo 'opcache.max_accelerated_files=4000'; \
+    echo 'opcache.revalidate_freq=2'; \
+    echo 'opcache.fast_shutdown=1'; \
+    } > /usr/local/etc/php/conf.d/opcache-recommended.ini
+# https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
+RUN { \
+    # https://www.php.net/manual/en/errorfunc.constants.php
+    # https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
+    echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+    echo 'display_errors = Off'; \
+    echo 'display_startup_errors = Off'; \
+    echo 'log_errors = On'; \
+    echo 'error_log = /dev/stderr'; \
+    echo 'log_errors_max_len = 1024'; \
+    echo 'ignore_repeated_errors = On'; \
+    echo 'ignore_repeated_source = Off'; \
+    echo 'html_errors = Off'; \
+    } > /usr/local/etc/php/conf.d/error-logging.ini
 
-# yumのアップデート
-RUN yum update -y &&\
-    yum clean all
 
-# 必要なモジュールのインストール(apache）
-RUN yum -y install httpd &&\
-    yum clean all
+ENV WORDPRESS_VERSION 5.4.2
+ENV WORDPRESS_SHA1 e5631f812232fbd45d3431783d3db2e0d5670d2d
 
-# 必要なモジュールのインストール（php7.4）
-RUN yum -y install php74-php php74-php-mysqli php74-php-gd php74-php-mbstring php74-php-opcache php74-php-xml php74-php-pear php74-php-devel php74-php-pecl-imagick php74-php-pecl-imagick-devel php74-php-pecl-zip
+RUN set -ex; \
+    curl -o wordpress.tar.gz -fSL "https://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz"; \
+    echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c -; \
+    # upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
+    tar -xzf wordpress.tar.gz -C /usr/src/; \
+    rm wordpress.tar.gz; \
+    chown -R www-data:www-data /usr/src/wordpress; \
+    # pre-create wp-content (and single-level children) for folks who want to bind-mount themes, etc so permissions are pre-created properly instead of root:root
+    mkdir wp-content; \
+    for dir in /usr/src/wordpress/wp-content/*/; do \
+    dir="$(basename "${dir%/}")"; \
+    mkdir "wp-content/$dir"; \
+    done; \
+    chown -R www-data:www-data wp-content; \
+    chmod -R 777 wp-content
 
-# phpコマンドを作成
-RUN ln /usr/bin/php74 /usr/bin/php
+VOLUME /var/www/html
 
-# wordpressインストールディレクトリの所有者をapacheユーザに変更                                              
-RUN chown -R apache:apache /var/www/html
+COPY docker-entrypoint.sh /usr/local/bin/
 
-# ｐｈｐ７４−ｐｈｐ−ｆｐｍのサービス永続化
-#RUN systemctl enable php74-php-fpm
-
-# apache サーバのサービス永続化
-#RUN systemctl enable httpd 
-
-# 接続用ポートの穴あけ
-EXPOSE 8010
-
-ENTRYPOINT /usr/sbin/httpd -D FOREGROUND
-CMD ["apache2-foreground"]
-
+ENTRYPOINT ["docker-entrypoint.sh"]
+CMD ["php-fpm"]
+EXPOSE 80
